# Generated by Django 5.1 on 2025-10-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
