# Generated by Django 6.0.5 on 2026-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_enquiry_options_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfollowup',
            name='status',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('planning', 'Planning'), ('under_review', 'Under Review'), ('on_hold', 'On Hold'), ('trader', 'Trader'), ('class_joined', 'Class Joined'), ('class_completed', 'Class Completed'), ('not_interested', 'Not Interested')], default='interested', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrmfollowup',
            name='status',
            field=models.CharField(blank=True, choices=[('interested', 'Interested'), ('planning', 'Planning'), ('under_review', 'Under Review'), ('on_hold', 'On Hold'), ('trader', 'Trader'), ('class_joined', 'Class Joined'), ('class_completed', 'Class Completed'), ('not_interested', 'Not Interested')], default='interested', max_length=30, null=True),
        ),
    ]
