# Generated by Django 5.1 on 2026-01-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_batch_options_batch_batch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_branch', to='AdminApp.branch'),
        ),
    ]
