# Generated by Django 5.1 on 2026-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('is_website_manager', 'Website Manager'), ('is_crm_manager', 'CRM Manager'), ('is_enrollment', 'Enrollment Manager'), ('is_crm_and_enrollment', 'CRM & Enrollment Manager'), ('is_staff', 'Staff'), ('is_student', 'Student')], default='is_student', max_length=30, null=True),
        ),
    ]
