# Generated by Django 5.1 on 2025-10-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_freecourse_freecourseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
