# Generated by Django 5.1 on 2025-10-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
