# Generated by Django 5.1 on 2025-10-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_customuser_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
