# Generated by Django 5.1 on 2025-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_freecourse_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecourse',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='free_courses/thumbnails/'),
        ),
    ]
