# Generated by Django 5.1 on 2025-10-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_freecourse_thumbnail'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
