# Generated by Django 5.1 on 2025-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance_to_Pro_Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.CharField(help_text='e.g. 25 October (Saturday)', max_length=100)),
                ('time', models.CharField(help_text='e.g. 06:00 PM', max_length=50)),
                ('duration', models.CharField(help_text='e.g. 2 Months', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_reviews', models.CharField(help_text='e.g. 16k+', max_length=50)),
                ('offer_price', models.CharField(default='Free', max_length=20)),
                ('original_price', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Basic_to_Advance_Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.CharField(help_text='e.g. 25 October (Saturday)', max_length=100)),
                ('time', models.CharField(help_text='e.g. 06:00 PM', max_length=50)),
                ('duration', models.CharField(help_text='e.g. 2 Months', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_reviews', models.CharField(help_text='e.g. 16k+', max_length=50)),
                ('offer_price', models.CharField(default='Free', max_length=20)),
                ('original_price', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
