# Generated by Django 5.1 on 2025-11-03 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_advance_to_pro_cource_basic_to_advance_cource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(db_index=True, help_text='Unique certificate number (e.g., C-1001)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Enter the course or certificate title (e.g., Advanced Web Design)', max_length=150)),
                ('issued_to', models.CharField(help_text='Full name of the recipient (e.g., Jane Doe)', max_length=100)),
                ('issued_by', models.CharField(help_text='Name of the institution or academy issuing this certificate (e.g., VR Academy)', max_length=100)),
                ('issue_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this certificate was issued')),
                ('description', models.TextField(blank=True, help_text='Short description of the course or achievement', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload the certificate image', null=True, upload_to='certificates/')),
                ('tag', models.CharField(default='Verified', help_text='Enter a tag like Verified, Pending, Expired, etc.', max_length=50)),
                ('rating', models.PositiveIntegerField(default=4, help_text='Rating out of 5 for this certificate or course')),
                ('model_name', models.CharField(blank=True, help_text='Optional field for related model or category name', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
