# Generated by Django 5.1 on 2025-11-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Certificate / Award', 'verbose_name_plural': 'Certificates & Awards'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='model_name',
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this certificate from the website'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_id',
            field=models.CharField(help_text='Unique ID for the certificate (e.g., C-1001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, help_text='Short description about the certificate or award (optional)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(help_text='Date when the certificate was issued'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_by',
            field=models.CharField(help_text='Organization or institution that issued the certificate', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_to',
            field=models.CharField(help_text='Name of the recipient', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Star rating (1–5) for the recognition'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tag',
            field=models.CharField(default='Verified', help_text='Short label such as Verified, Awarded, Achieved, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(help_text='Name of the certificate or recognition title', max_length=255),
        ),
    ]
