# Generated by Django 5.1 on 2025-11-04 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cert_id',
        ),
    ]
