# Generated by Django 5.1 on 2025-11-13 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0015_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload event thumbnail image', null=True, upload_to='event_thumbnails/')),
                ('title', models.CharField(help_text='Enter the main title of the event', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Add an optional subtitle for the event', max_length=300, null=True)),
                ('description', models.TextField(blank=True, help_text='Write a detailed description of the event', null=True)),
                ('category', models.CharField(blank=True, help_text='Specify the category or type of event (e.g., Webinar, Workshop)', max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of keywords related to the event (e.g., ['Technology', 'Education'])")),
                ('event_date', models.DateField(help_text='Select the event date')),
                ('event_start_time', models.TimeField(help_text='Enter the start time of the event')),
                ('event_end_time', models.TimeField(help_text='Enter the end time of the event')),
                ('timezone', models.CharField(default='IST', help_text='Specify the event timezone', max_length=50)),
                ('meeting_link', models.URLField(blank=True, help_text='Add meeting link if applicable (e.g., Zoom or Google Meet URL)', null=True)),
                ('meeting_id', models.CharField(blank=True, help_text='Enter meeting ID if required', max_length=100, null=True)),
                ('meeting_password', models.CharField(blank=True, help_text='Enter meeting password if required', max_length=100, null=True)),
                ('is_free', models.BooleanField(default=False, help_text='Check if the event is free to attend')),
                ('registration_strickthrough_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Enter original registration fee (for strikethrough display)', max_digits=10, null=True)),
                ('registration_offer_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter discounted or current registration fee', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', help_text='Select current event status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when event is created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updates when event is modified')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date and time when event was published', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
