# Generated by Django 5.1 on 2025-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_event_alter_passwordresetotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of keywords related to the event (e.g., ['Technology', 'Education'])", null=True),
        ),
    ]
