# Generated by Django 5.2.6 on 2025-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0018_alter_event_thumbnail_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
