# Generated by Django 5.1 on 2025-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0018_alter_event_thumbnail_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance_to_pro_cource',
            name='new_batch_start_slug',
            field=models.CharField(blank=True, help_text='e.g. New Batch Start', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basic_to_advance_cource',
            name='new_batch_start_slug',
            field=models.CharField(blank=True, help_text='e.g. New Batch Start', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
