# Generated by Django 5.1 on 2025-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0019_advance_to_pro_cource_new_batch_start_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecourse',
            name='duration',
            field=models.CharField(blank=True, help_text='ex.15 Days, 2 Months', max_length=50, null=True),
        ),
    ]
