# Generated by Django 5.1 on 2025-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0020_freecourse_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('website_manager', 'Website Manager'), ('crm_manager', 'CRM Manager'), ('staff', 'Staff'), ('student', 'Student')], default='student', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='freecourse',
            name='duration',
            field=models.CharField(blank=True, help_text='ex.15 Days, 2 Months, 45 min', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='video_link',
            field=models.CharField(blank=True, help_text='Enter YouTube video link', max_length=500, null=True),
        ),
    ]
