# Generated by Django 5.1 on 2025-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0021_customuser_role_alter_freecourse_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('is_website_manager', 'Website Manager'), ('is_crm_manager', 'CRM Manager'), ('is_staff', 'Staff'), ('is_student', 'Student')], default='is_student', max_length=30, null=True),
        ),
    ]
