# Generated by Django 5.1 on 2025-12-25 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0022_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_Student_Interested_for_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CRMFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('walkin', 'Walk-in'), ('reference', 'Reference')], default='website', max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('interested', 'Interested'), ('planning', 'Planning'), ('under_review', 'Under Review'), ('on_hold', 'On Hold'), ('class_joined', 'Class Joined'), ('class_completed', 'Class Completed'), ('not_interested', 'Not Interested')], default='interested', max_length=30, null=True)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20, null=True)),
                ('call_response', models.CharField(blank=True, choices=[('answered', 'Answered'), ('not_answered', 'Not Answered'), ('busy', 'Busy'), ('switched_off', 'Switched Off')], max_length=20, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('next_followup_reminder', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('class_start_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('student_interested_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.crm_student_interested_for_options')),
            ],
        ),
    ]
