# Generated by Django 5.1 on 2025-12-25 05:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0023_crm_student_interested_for_options_crmfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCRMFollowup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('walkin', 'Walk-in'), ('reference', 'Reference')], default='website', max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[('interested', 'Interested'), ('planning', 'Planning'), ('under_review', 'Under Review'), ('on_hold', 'On Hold'), ('class_joined', 'Class Joined'), ('class_completed', 'Class Completed'), ('not_interested', 'Not Interested')], default='interested', max_length=30, null=True)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20, null=True)),
                ('call_response', models.CharField(blank=True, choices=[('answered', 'Answered'), ('not_answered', 'Not Answered'), ('busy', 'Busy'), ('switched_off', 'Switched Off')], max_length=20, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('next_followup_reminder', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('class_start_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical crm followup',
                'verbose_name_plural': 'historical crm followups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='crmfollowup',
            index=models.Index(fields=['status', 'priority'], name='AdminApp_cr_status_ae2dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfollowup',
            index=models.Index(fields=['follow_up_date'], name='AdminApp_cr_follow__a8c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmfollowup',
            index=models.Index(fields=['next_followup_reminder'], name='AdminApp_cr_next_fo_e4e041_idx'),
        ),
        migrations.AddField(
            model_name='historicalcrmfollowup',
            name='follow_up_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcrmfollowup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcrmfollowup',
            name='student_interested_for',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='AdminApp.crm_student_interested_for_options'),
        ),
    ]
