# Generated by Django 5.1 on 2025-12-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0024_historicalcrmfollowup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='is_added_in_CRMFollowup_model',
            field=models.BooleanField(default=False),
        ),
    ]
