# Generated by Django 5.2.6 on 2025-12-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0019_alter_eventregistration_registration_id'),
        ('AdminApp', '0025_enquiry_is_added_in_crmfollowup_model'),
    ]

    operations = [
    ]
