# Generated by Django 5.1 on 2025-12-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0026_branch_city_crmfollowup_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='crmfollowup',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='historicalcrmfollowup',
            old_name='city',
            new_name='address',
        ),
    ]
