# Generated by Django 5.1 on 2025-12-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0027_rename_city_address_rename_city_crmfollowup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfollowup',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrmfollowup',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
