# Generated by Django 5.1 on 2025-12-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0028_alter_crmfollowup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmfollowup',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrmfollowup',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
