"""
Django settings for VRACADEMYHUB project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l-zq3uu6&^46d2#2e0=x%3dvs+d)iw&h0qq)ha1h$a&_$pumt4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['vracademyhub.com',
    'www.vracademyhub.com',
    '72.60.96.41',
    'localhost',
    '127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'WebApp',
    'AdminApp',
    'StudentApp',
    'SoftwareApp',
    'crispy_forms',
    'crispy_bootstrap5',
    'simple_history',
]


JAZZMIN_SETTINGS = {
    "icons": {
        "yourapp.Enquiry": "fas fa-envelope-open-text",  # or any FontAwesome icon
    },
}


MIDDLEWARE = [
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VRACADEMYHUB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VRACADEMYHUB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('hi', _('Hindi')),
    ('mr', _('Marathi')),
]

LANGUAGE_CODE = 'en'   # Default language

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Location of translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]




# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True

AUTH_USER_MODEL = 'AdminApp.CustomUser'
LOGIN_URL = '/login'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Razorpay Configuration

#test api keys
RAZORPAY_KEY_ID = 'rzp_test_RfELpk3eZdngJZ' 
#test api secret keys
RAZORPAY_KEY_SECRET = 'lWVYlpQE8ftiRcrmfv1M8arF'


STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# STATIC_ROOT = "/VRACADEMYHUB/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'


import os
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
 
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




JAZZMIN_SETTINGS = {
    "site_title": "VR ACADEMY HUB",
    "site_header": "VR ACADEMY HUB",
    "site_brand": "VR ACADEMY HUB",
    "welcome_sign": "Welcome to VR ACADEMY HUB Dashboard",
    "copyright": "© 2025 VR Training Academy",

    # Optional — customize logo & icons
    "site_logo": "website/img/logo.png",  # path inside STATIC files
    "login_logo": "website/img/logo-for-admin-login.png",
    "site_logo_classes": "img-circle",
    "site_icon": None,

    # Optional — change background/theme colors
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "AdminApp"},  # example
    ],

    # Side menu
    "show_sidebar": True,
    "navigation_expanded": True, 

    # UI tweaks
    "theme": "pulse",  # You can try: flatly, pulse, cyborg, solar, etc.
    "custom_css": None,
    "custom_js": None,
}


JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark bg-primary",
    "accent": "accent-primary",
    "theme": "pulse",
}




# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'vrtrainingacademy@gmail.com'  # Replace with your Gmail email address
EMAIL_HOST_PASSWORD = 'lawo tafh hxwd bqok'  # Replace with your Gmail password or App Password

# CSRF_TRUSTED_ORIGINS = [
#     'https://sailanddevelopers.com',
#     'https://www.sailanddevelopers.com',  # If using both www and non-www versions
#     'http://sailanddevelopers.com',  # Add HTTP for local or non-SSL traffic, if necessary
#     'http://www.sailanddevelopers.com',  # Add HTTP for local or non-SSL traffic, if necessary
# ]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
